# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-01-10 14:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
from django.conf import settings

CUSTOM_INVITER_MODEL = getattr(settings, 'INVITATIONS_CUSTOM_INVITER_MODEL', settings.AUTH_USER_MODEL)

class Migration(migrations.Migration):

    dependencies = [
        ('invitations', '0003_auto_20151126_1523'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invitation',
            name='inviter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=CUSTOM_INVITER_MODEL),
        ),
    ]

